version: '3.6'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - services-tier
  node-solzhenitsyn:
    container_name: node-solzhenitsyn
    restart: always
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GATE_LISTEN_PORT:$GATE_LISTEN_PORT
    environment:
      - GATE_LISTEN_PORT
      - DAY_START
      - MONGO_CONNECT_STRING
      - BLOCKCHAIN_SUBSCRIBE_TIMEOUT
      - BLOCKCHAIN_NODE_ADDRESS
      - METRICS_HOST
      - METRICS_PORT

networks:
  services-tier:
